import atom
import bond

def print_atoms(atom,extra = False):
    for k in range(0,len(atom)):
       print "Atom id: %s" % atom[k].atom_id
       if atom[k].atom_id == "116":
           for i in range(0,len(atom[k].atom_bonds)):
               print atom[k].atom_bonds[i].atom_id
       print "Atom type: %s" % atom[k].atom_type
       print "X position: %s" % atom[k].x_pos
       print "Y position: %s" % atom[k].y_pos
       print "Z position: %s" % atom[k].z_pos
       print "Atoms bonded to %s" % atom[k].atom_bonds
       print "Number of bonds %s" % atom[k].numbonds
       if extra:
           print "OPLS id %s" % atom[k].opls_id
           print "OPLS bond id %s" % atom[k].opls_bondid
           print "OPLS sigma %s" % atom[k].opls_sigma
           print "OPLS epsilon %s" % atom[k].opls_epsilon
           print "OPLS partial charge %s" % atom[k].opls_partial
           print "OPLS atomic mass %s" % atom[k].opls_mass
       print ""

def print_bonds(bond,boo = False):
    """ Prints a list of bond objects created by create_bondobj

    Keyword Arguments:
    bond -- The list of bond objects to pass in and print
    """
    print "   BONDS   "
    print "-----------"
    for z in range(0, len(bond)):
       print "Bond Type: %s" % bond[z].bond_type
       print "Bond Master(bonded from): %s" % bond[z].bond_master.atom_id
       print "Bond Slave(bonded to): %s" % bond[z].bond_slave.atom_id
       print "Bond Master Type: %s" % bond[z].bond_master.atom_type
       print "Bond Slave Type: %s" % bond[z].bond_slave.atom_type
       print "Bond Number %s" % z
       if boo:
           print "OPLS Force Constant: %s" % bond[z].bond_force_const
           print "OPLS Equilibrium Length: %s" % bond[z].bond_equib_len
       print ""

def print_angles(AngleList,boo = False):
    """
    Given a list of angles, print the angle id's

    Keyword Arguments:
    AngleList -- The list of angles to print
    """
    for x in range(0,len(AngleList)):
        print "Angle number %s" % x
        print "Angle Type: %s" % AngleList[x].Angle_type
        print "Master Angle: %s" % AngleList[x].Angle_master.atom_id
        print "Slave angle 1: %s" % AngleList[x].Angle_slave1.atom_id
        print "Slave angle 2: %s" % AngleList[x].Angle_slave2.atom_id
        if boo:
            print "Master Angle Bond: %s" % AngleList[x].Angle_master.opls_bondid
            print "Slave Angle Bond: %s" % AngleList[x].Angle_slave1.opls_bondid
            print "Slave Angle2 Bond: %s" % AngleList[x].Angle_slave2.opls_bondid
            if AngleList[x].Angle_equib_len == "":
                print "no good data"
                continue
            print "Equilibrium length %s" % AngleList[x].Angle_equib_len
            print "Force Constant: %s" % AngleList[x].Angle_force_const
        print ""

def print_dihedrals(dihedrals):
    """ Print the atom id's of a list of dihedrals

    Keyword Arguments:
    dihedrals -- the list of dihedrals to print
    """
    print "DIHEDRALS"
    print "---------"
    for i in range(0,len(dihedrals)):
        print "Dihedral %s: %s" % (i,dihedrals[i])
        print "Dihedral Master1 %s" % (dihedrals[i].dihedral_master1.atom_id)
        print "Dihedral Master2 %s" % (dihedrals[i].dihedral_master2.atom_id)
        print "Dihedral Slave1 %s" % (dihedrals[i].dihedral_slave1.atom_id)
        print "Dihedral Slave2 %s" % (dihedrals[i].dihedral_slave2.atom_id)

def print_ring(rings):
    """ Prints the atom id's from what is contained in the Ring list.

    Keyword Arguments:
    rings -- The list of rings to print and get atom id's from
    """
    print "----------RINGS----------"
    for k in range(0,len(rings)):
        print ""
        print "ring number %d" % k
        print rings[k]
        print rings[k].atom1.atom_id
        print rings[k].atom2.atom_id
        print rings[k].atom3.atom_id
        print rings[k].atom4.atom_id
        print rings[k].atom5.atom_id
        if rings[k].ring_type == 6:
            print rings[k].atom6.atom_id

def print_fused(fused):
    """ Prints the fused rings found by the find_fused method. Is void.

        Keyword Arguments:
        fused - The list of fused rings generated by find_fused
    """
    print "----------FUSED RINGS---------"
    for i in range(0,len(fused)):
        print ""
        print "fused 1 %s" % fused[i].ring1
        print "fused 2 %s" % fused[i].ring2

def print_opls_atoms(opls_atoms):
    """ Prints the list of opls atoms created earlier in this file

        Keyword Arguments:
        opls_atoms - The list of opls atoms to print
    """
    print "----------OPLS ATOMS----------"
    for i in range(0,len(opls_atoms)):
        print ""
        print opls_atoms[i].opls_id
        print opls_atoms[i].opls_bondid
        print opls_atoms[i].opls_type
        print opls_atoms[i].pc
        print opls_atoms[i].sigma
        print opls_atoms[i].epsilon
        print opls_atoms[i].amass

def print_opls_bonds(opls_bonds):
    """ Prints the list of opls bonds created earlier in this file

        Keyword Arguments:
        opls_bonds - The list of opls bond to print
    """
    print "----------OPLS BONDS----------"
    for i in range(0,len(opls_bonds)):
        print ""
        print opls_bonds[i].opls_master
        print opls_bonds[i].opls_slave
        print opls_bonds[i].fc
        print opls_bonds[i].el

def print_opls_angles(opls_angles):
    """ Prints the list of opls angles created earlier in this file

        Keyword Arguments:
        opls_angles - The list of opls angles to print
    """
    print "----------OPLS ANGLES----------"
    for i in range(0,len(opls_angles)):
        print ""
        print opls_angles[i].opls_master
        print opls_angles[i].opls_slave1
        print opls_angles[i].opls_slave2
        print opls_angles[i].fc
        print opls_angles[i].el

def print_opls_dihedrals(opls_dihedrals):
    print "----------OPLS DIHEDRALS----------"
    for i in range(len(opls_dihedrals)):
        print ""
        print opls_dihedrals[i].opls_master1
        print opls_dihedrals[i].opls_master2
        print opls_dihedrals[i].opls_slave1
        print opls_dihedrals[i].opls_slave2
        print opls_dihedrals[i].k1
        print opls_dihedrals[i].k2
        print opls_dihedrals[i].k3
        print opls_dihedrals[i].k4
